### ISSUE TITLE
AutoAccept

### ISSUE THREAD

**Issue by Alexander01998** [Wurst-Imperium/Wurst-file-converter#12]

**Comment by mcccs** [comment]
@Alexander01998 Are you sure you're in the right repository?

**Comment by Alexander01998** [comment]
> @Alexander01998 Are you sure you're in the right repository?

Yes. I am using this repository as a secret Issue Tracker for Wurst so that the spammers won't find it.

Back in the day when I had Wurst-Imperium/Wurst-Client/issues, people kept duplicating existing issues, submitting multiple suggestions by creating only one issue and, worst of all, spamming "Add Optifine & AntiBan!!1".

In this repo, I take suggestions from the YouTube & Disqus comments, things I find in forks that I want to merge as well as some of my own ideas and then create issues here so that I won't forget them. And because all of the issues here are created by me, I don't need to worry about removing duplicates, rejecting bad suggestions, dealing with haters, etc. I also use the ZenHub extension so that I can manage the issues across different repositories.

I knew that people like you and pokeball would eventually find this repo, but I know you wouldn't spam here.

This would all be much easier if GitHub had support for restricting issues to collaborators, but so far, they haven't added it. I'm pretty sure I suggested that feature more than once to them.
