### ISSUE TITLE
GodMode

### ISSUE THREAD

**Issue by Alexander01998** [Wurst-Imperium/Wurst-file-converter#15]
The thing that lets you walk around after dying.

Untested. See: https://github.com/ThisTestUser/Wurst-Client-for-MC-1.9.X/blob/7d32693099ef1ef45b259edebe43177218244ec1/Wurst%20Client%20for%20MC%201.9.X/src/tk/wurst_client/mods/GhostMod.java

**Comment by ThisTestUser** [comment]
It's actually not a GodMode, as you cannot interact.
Also that CrashBook appears to crash you as well, and it is untested with other players.
ArmorBreaker is implanted like in other clients, but I don't know if it actually breaks the armor.

**Comment by Alexander01998** [comment]
That's why I added "Untested." to the descriptions of those issues.
